name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t uselesswhale1/sigma-chat-fe .
      - name: Publish image to docker hub
        run: docker push uselesswhale1/sigma-chat-fe:latest

  deploy:
    needs: build
    runs-on: aws-ec2-fe
    steps:
      - name: Pull image from docker hub
        run: docker pull uselesswhale1/sigma-chat-fe:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer uselesswhale1/sigma-chat-fe
